databases:
  - name: mdcat_expert_db
    databaseName: mdcat_expert
    user: mdcat_user

services:
  - type: web
    name: mdcat_expert
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mdcat_expert.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mdcat_expert_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: CLOUDINARY_URL
        sync: false
